// Generated by CoffeeScript 1.12.7
(function() {
  $.fn.extend({
    removeClassWild: function(mask) {
      return this.removeClass(function(index, cls) {
        var re;
        re = mask.replace(/\*/g, '\\S+');
        return (cls.match(new RegExp('\\b' + re + '', 'g')) || []).join(' ');
      });
    },
    iconToggle: function(newClass) {
      $(this).removeClassWild('icon-*');
      return $(this).addClass(newClass);
    }
  });

}).call(this);

//# sourceMappingURL=help.lib.js.map
